create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  title text not null,
  is_complete boolean default false not null,
  inserted_at timestamptz default timezone('utc'::text, now()) not null
);

comment on table public.todos is 'Stores user todos.';

alter table public.todos enable row level security;

create policy "Users can view own todos"
  on public.todos for select
  using ( auth.uid() = user_id );

create policy "Users can insert own todos"
  on public.todos for insert
  with check ( auth.uid() = user_id );

create policy "Users can update own todos"
  on public.todos for update
  using ( auth.uid() = user_id );

create policy "Users can delete own todos"
  on public.todos for delete
  using ( auth.uid() = user_id );

create index if not exists todos_user_id_idx on public.todos (user_id);
