-- Create todos table
create table public.todos (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text check (char_length(title) > 3),
  is_complete boolean default false,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.todos enable row level security;

-- Create policies
create policy "Individuals can create todos." on public.todos for insert with check (auth.uid() = user_id);
create policy "Individuals can view their own todos. " on public.todos for select using (auth.uid() = user_id);
create policy "Individuals can update their own todos." on public.todos for update using (auth.uid() = user_id);
create policy "Individuals can delete their own todos." on public.todos for delete using (auth.uid() = user_id);
