create table todos (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text,
  is_complete boolean default false,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table todos enable row level security;

create policy "Users can view their own todos." on todos for select using (auth.uid() = user_id);
create policy "Users can insert their own todos." on todos for insert with check (auth.uid() = user_id);
create policy "Users can update their own todos." on todos for update using (auth.uid() = user_id);
create policy "Users can delete their own todos." on todos for delete using (auth.uid() = user_id);

create index todos_user_id_idx on todos (user_id);
